name: Build website
on:
  push:
    branches: [master]
  pull_request:
    # Check all PR

jobs:
  build-website:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      # we need the full history to be able to get the chemiscope version with
      # git describe during the build
      with:
        fetch-depth: 0
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: install npm dependencies
      uses: bahmutov/npm-install@v1
    - name: install python dependencies
      run: |
        python3 -m pip install -r docs/requirements.txt
        python3 -m pip install beautifulsoup4 requests
    - run: npm run build
    - run: npm run download-example-input
    - run: cd docs && make html
    - run: python3 utils/generate_standalone.py -o chemiscope_standalone.html
    - name: assemble full website
      run: |
          cp -r app/ gh-pages/
          cp dist/*.min.js gh-pages/
          cp chemiscope_standalone.html gh-pages/
          cp -r docs/_build/html/ gh-pages/docs/
          tar czf gh-pages.tar.gz gh-pages/
    - name: upload built website archive
      uses: actions/upload-artifact@v1
      with:
          name: website
          path: gh-pages.tar.gz

  deploy-website:
    needs: build-website
    # only deploy if we are in the master branch
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - name: download build website
        uses: actions/download-artifact@v2
        with:
          name: website
      - name: extract website
        run: tar xf gh-pages.tar.gz
      - name: deploy website to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./gh-pages/
